spring:
  application:
    name: chatting
  datasource:
    url: jdbc:h2:tcp://localhost/~/chatting
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect